#!/bin/bash
# =============================================================================
# TESSERA — Fabric CA Identity Registration Script
#
# Registers and enrolls ALL identities for the TESSERA network using Fabric CA.
# This replaces cryptogen — all crypto material is generated by the CAs.
#
# Organizations and identities registered:
#
# OrdererOrg (ca.orderer.tessera.com:8054)
#   orderer-admin     — org admin
#   orderer.tessera.com — orderer node (MSP + TLS)
#
# IssuerOrg (ca.issuer.tessera.com:7054)
#   issuer-admin      — org admin (org-level admin)
#   peer0.issuer      — peer node (MSP + TLS)
#   issuer-user       — business user (asset registrar)
#   auditor-user      — auditor (cross-org read access in Phase 4)
#
# VerifierOrg (ca.verifier.tessera.com:9054)
#   verifier-admin    — org admin
#   peer0.verifier    — peer node (MSP + TLS)
#   verifier-user     — business user (evidence verifier)
#
# ComplianceOrg (ca.compliance.tessera.com:10054)
#   compliance-admin  — org admin
#   peer0.compliance  — peer node (MSP + TLS)
#   compliance-user   — business user (compliance officer)
#
# Usage:
#   ./blockchain/scripts/register-identities.sh
#
# Prerequisites:
#   CA containers must be running (docker compose up -d ca.*.tessera.com)
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/utils.sh"

# ============================================================
# CA connection parameters
# ============================================================
CA_ORDERER_HOST="localhost:8054"
CA_ISSUER_HOST="localhost:7054"
CA_VERIFIER_HOST="localhost:9054"
CA_COMPLIANCE_HOST="localhost:10054"

# Load credentials from .env if present
ENV_FILE="${TESSERA_ROOT}/.env"
if [ -f "${ENV_FILE}" ]; then
  set -a; source "${ENV_FILE}"; set +a
fi

CA_ORDERER_ADMIN_USER="${CA_ORDERER_ADMIN_USER:-admin}"
CA_ORDERER_ADMIN_PASS="${CA_ORDERER_ADMIN_PASS:-adminpw}"
CA_ISSUER_ADMIN_USER="${CA_ISSUER_ADMIN_USER:-admin}"
CA_ISSUER_ADMIN_PASS="${CA_ISSUER_ADMIN_PASS:-adminpw}"
CA_VERIFIER_ADMIN_USER="${CA_VERIFIER_ADMIN_USER:-admin}"
CA_VERIFIER_ADMIN_PASS="${CA_VERIFIER_ADMIN_PASS:-adminpw}"
CA_COMPLIANCE_ADMIN_USER="${CA_COMPLIANCE_ADMIN_USER:-admin}"
CA_COMPLIANCE_ADMIN_PASS="${CA_COMPLIANCE_ADMIN_PASS:-adminpw}"

# ============================================================
# Helper: Enroll an identity
# ============================================================
enrollIdentity() {
  local caClientHome="$1"
  local caUrl="$2"
  local caName="$3"
  local enrollId="$4"
  local enrollSecret="$5"
  local mspDir="$6"
  local tlsCertFile="$7"
  local profile="${8:-}"
  local csrHosts="${9:-}"

  mkdir -p "${caClientHome}" "${mspDir}"

  local extraArgs=""
  [ -n "${profile}" ]  && extraArgs="${extraArgs} --enrollment.profile ${profile}"
  [ -n "${csrHosts}" ] && extraArgs="${extraArgs} --csr.hosts ${csrHosts}"

  FABRIC_CA_CLIENT_HOME="${caClientHome}" \
    ${FABRIC_CA_CLIENT} enroll \
      -u "https://${enrollId}:${enrollSecret}@${caUrl}" \
      --caname "${caName}" \
      --mspdir "${mspDir}" \
      --tls.certfiles "${tlsCertFile}" \
      ${extraArgs}
}

# ============================================================
# Helper: Register an identity (must be run as CA admin)
# ============================================================
registerIdentity() {
  local caClientHome="$1"
  local caName="$2"
  local id="$3"
  local secret="$4"
  local type="$5"
  local tlsCertFile="$6"

  FABRIC_CA_CLIENT_HOME="${caClientHome}" \
    ${FABRIC_CA_CLIENT} register \
      --caname "${caName}" \
      --id.name "${id}" \
      --id.secret "${secret}" \
      --id.type "${type}" \
      --tls.certfiles "${tlsCertFile}" 2>&1 || true
  # || true: fabric-ca-client register returns non-zero if identity already exists;
  # this is idempotent — existing identities are left as-is.
}

# ============================================================
# enrollOrdererOrg
# ============================================================
enrollOrdererOrg() {
  header "Enrolling OrdererOrg identities"

  local caName="ca.orderer.tessera.com"
  local caHost="${CA_ORDERER_HOST}"
  local caFabricDir="${ORG_DIR}/fabric-ca/orderer"
  local tlsCert="${caFabricDir}/tls-cert.pem"
  local ordererOrgDir="${ORG_DIR}/ordererOrganizations/tessera.com"
  local caAdminHome="${ordererOrgDir}/ca-admin"

  waitForCA "https://${caHost}" "${caName}"

  # 1. Enroll CA bootstrap admin
  step "Enrolling CA bootstrap admin for OrdererOrg"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "${CA_ORDERER_ADMIN_USER}" "${CA_ORDERER_ADMIN_PASS}" \
    "${caAdminHome}/msp" "${tlsCert}"

  # 2. Register orderer admin
  step "Registering orderer-admin"
  registerIdentity "${caAdminHome}" "${caName}" "orderer-admin" "adminpw" "admin" "${tlsCert}"

  # 3. Register orderer node
  step "Registering orderer.tessera.com node"
  registerIdentity "${caAdminHome}" "${caName}" "orderer.tessera.com" "ordererpw" "orderer" "${tlsCert}"

  # 4. Enroll orderer admin MSP
  step "Enrolling orderer-admin MSP"
  local adminMspDir="${ordererOrgDir}/users/Admin@tessera.com/msp"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "orderer-admin" "adminpw" "${adminMspDir}" "${tlsCert}"

  # 5. Enroll orderer node MSP
  step "Enrolling orderer.tessera.com MSP"
  local ordererMspDir="${ordererOrgDir}/orderers/orderer.tessera.com/msp"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "orderer.tessera.com" "ordererpw" "${ordererMspDir}" "${tlsCert}"

  # 6. Enroll orderer node TLS
  step "Enrolling orderer.tessera.com TLS"
  local ordererTlsEnrollDir="${ordererOrgDir}/orderers/orderer.tessera.com/tls-enrollment"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "orderer.tessera.com" "ordererpw" "${ordererTlsEnrollDir}" "${tlsCert}" \
    "tls" "orderer.tessera.com,localhost,127.0.0.1"

  installTLSCerts \
    "${ordererTlsEnrollDir}" \
    "${ordererOrgDir}/orderers/orderer.tessera.com/tls"

  # 7. Set up org-level MSP
  step "Setting up OrdererOrg MSP"
  local orgMspDir="${ordererOrgDir}/msp"
  mkdir -p "${orgMspDir}/cacerts" "${orgMspDir}/tlscacerts"
  cp "${caFabricDir}/ca-cert.pem" "${orgMspDir}/cacerts/ca-cert.pem"
  cp "${ordererOrgDir}/orderers/orderer.tessera.com/tls/ca.crt" "${orgMspDir}/tlscacerts/ca-cert.pem"
  writeMSPConfig "${orgMspDir}" "ca-cert.pem"

  # 8. Copy CA cert into user MSP for config.yaml
  mkdir -p "${ordererOrgDir}/users/Admin@tessera.com/msp/cacerts"
  cp "${caFabricDir}/ca-cert.pem" "${ordererOrgDir}/users/Admin@tessera.com/msp/cacerts/ca-cert.pem"
  writeMSPConfig "${ordererOrgDir}/users/Admin@tessera.com/msp" "ca-cert.pem"

  # 9. Copy CA cert into orderer node MSP
  mkdir -p "${ordererMspDir}/cacerts" "${ordererMspDir}/tlscacerts"
  cp "${caFabricDir}/ca-cert.pem" "${ordererMspDir}/cacerts/ca-cert.pem"
  cp "${ordererOrgDir}/orderers/orderer.tessera.com/tls/ca.crt" "${ordererMspDir}/tlscacerts/ca-cert.pem"
  writeMSPConfig "${ordererMspDir}" "ca-cert.pem"

  success "OrdererOrg identities enrolled."
}

# ============================================================
# enrollIssuerOrg
# ============================================================
enrollIssuerOrg() {
  header "Enrolling IssuerOrg identities"

  local caName="ca.issuer.tessera.com"
  local caHost="${CA_ISSUER_HOST}"
  local caFabricDir="${ORG_DIR}/fabric-ca/issuer"
  local tlsCert="${caFabricDir}/tls-cert.pem"
  local issuerOrgDir="${ORG_DIR}/peerOrganizations/issuer.tessera.com"
  local caAdminHome="${issuerOrgDir}/ca-admin"

  waitForCA "https://${caHost}" "${caName}"

  # 1. Enroll CA bootstrap admin
  step "Enrolling CA bootstrap admin for IssuerOrg"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "${CA_ISSUER_ADMIN_USER}" "${CA_ISSUER_ADMIN_PASS}" \
    "${caAdminHome}/msp" "${tlsCert}"

  # 2. Register identities
  step "Registering IssuerOrg identities"
  registerIdentity "${caAdminHome}" "${caName}" "issuer-admin"        "adminpw"      "admin"  "${tlsCert}"
  registerIdentity "${caAdminHome}" "${caName}" "peer0.issuer"        "peer0pw"      "peer"   "${tlsCert}"
  registerIdentity "${caAdminHome}" "${caName}" "issuer-user"         "issueruserpw" "client" "${tlsCert}"
  registerIdentity "${caAdminHome}" "${caName}" "auditor-user"        "auditorpw"    "client" "${tlsCert}"

  # 3. Enroll org admin
  step "Enrolling issuer-admin MSP"
  local adminMspDir="${issuerOrgDir}/users/Admin@issuer.tessera.com/msp"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "issuer-admin" "adminpw" "${adminMspDir}" "${tlsCert}"

  # 4. Enroll peer MSP
  step "Enrolling peer0.issuer MSP"
  local peerMspDir="${issuerOrgDir}/peers/peer0.issuer.tessera.com/msp"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "peer0.issuer" "peer0pw" "${peerMspDir}" "${tlsCert}"

  # 5. Enroll peer TLS
  step "Enrolling peer0.issuer TLS"
  local peerTlsEnrollDir="${issuerOrgDir}/peers/peer0.issuer.tessera.com/tls-enrollment"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "peer0.issuer" "peer0pw" "${peerTlsEnrollDir}" "${tlsCert}" \
    "tls" "peer0.issuer.tessera.com,localhost,127.0.0.1"

  installTLSCerts \
    "${peerTlsEnrollDir}" \
    "${issuerOrgDir}/peers/peer0.issuer.tessera.com/tls"

  # 6. Enroll business users
  step "Enrolling issuer-user MSP"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "issuer-user" "issueruserpw" \
    "${issuerOrgDir}/users/issuer-user/msp" "${tlsCert}"

  step "Enrolling auditor-user MSP"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "auditor-user" "auditorpw" \
    "${issuerOrgDir}/users/auditor-user/msp" "${tlsCert}"

  # 7. Set up org-level MSP
  step "Setting up IssuerOrg MSP"
  local orgMspDir="${issuerOrgDir}/msp"
  mkdir -p "${orgMspDir}/cacerts" "${orgMspDir}/tlscacerts"
  cp "${caFabricDir}/ca-cert.pem" "${orgMspDir}/cacerts/ca-cert.pem"
  cp "${issuerOrgDir}/peers/peer0.issuer.tessera.com/tls/ca.crt" "${orgMspDir}/tlscacerts/ca-cert.pem"
  writeMSPConfig "${orgMspDir}" "ca-cert.pem"

  # 8. Patch peer MSP cacerts + config
  mkdir -p "${peerMspDir}/cacerts" "${peerMspDir}/tlscacerts"
  cp "${caFabricDir}/ca-cert.pem" "${peerMspDir}/cacerts/ca-cert.pem"
  cp "${issuerOrgDir}/peers/peer0.issuer.tessera.com/tls/ca.crt" "${peerMspDir}/tlscacerts/ca-cert.pem"
  writeMSPConfig "${peerMspDir}" "ca-cert.pem"

  # 9. Patch admin MSP cacerts + config
  mkdir -p "${adminMspDir}/cacerts"
  cp "${caFabricDir}/ca-cert.pem" "${adminMspDir}/cacerts/ca-cert.pem"
  writeMSPConfig "${adminMspDir}" "ca-cert.pem"

  success "IssuerOrg identities enrolled."
}

# ============================================================
# enrollVerifierOrg
# ============================================================
enrollVerifierOrg() {
  header "Enrolling VerifierOrg identities"

  local caName="ca.verifier.tessera.com"
  local caHost="${CA_VERIFIER_HOST}"
  local caFabricDir="${ORG_DIR}/fabric-ca/verifier"
  local tlsCert="${caFabricDir}/tls-cert.pem"
  local verifierOrgDir="${ORG_DIR}/peerOrganizations/verifier.tessera.com"
  local caAdminHome="${verifierOrgDir}/ca-admin"

  waitForCA "https://${caHost}" "${caName}"

  step "Enrolling CA bootstrap admin for VerifierOrg"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "${CA_VERIFIER_ADMIN_USER}" "${CA_VERIFIER_ADMIN_PASS}" \
    "${caAdminHome}/msp" "${tlsCert}"

  step "Registering VerifierOrg identities"
  registerIdentity "${caAdminHome}" "${caName}" "verifier-admin"  "adminpw"        "admin"  "${tlsCert}"
  registerIdentity "${caAdminHome}" "${caName}" "peer0.verifier"  "peer0pw"        "peer"   "${tlsCert}"
  registerIdentity "${caAdminHome}" "${caName}" "verifier-user"   "verifieruserpw" "client" "${tlsCert}"

  step "Enrolling verifier-admin MSP"
  local adminMspDir="${verifierOrgDir}/users/Admin@verifier.tessera.com/msp"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "verifier-admin" "adminpw" "${adminMspDir}" "${tlsCert}"

  step "Enrolling peer0.verifier MSP"
  local peerMspDir="${verifierOrgDir}/peers/peer0.verifier.tessera.com/msp"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "peer0.verifier" "peer0pw" "${peerMspDir}" "${tlsCert}"

  step "Enrolling peer0.verifier TLS"
  local peerTlsEnrollDir="${verifierOrgDir}/peers/peer0.verifier.tessera.com/tls-enrollment"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "peer0.verifier" "peer0pw" "${peerTlsEnrollDir}" "${tlsCert}" \
    "tls" "peer0.verifier.tessera.com,localhost,127.0.0.1"

  installTLSCerts \
    "${peerTlsEnrollDir}" \
    "${verifierOrgDir}/peers/peer0.verifier.tessera.com/tls"

  step "Enrolling verifier-user MSP"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "verifier-user" "verifieruserpw" \
    "${verifierOrgDir}/users/verifier-user/msp" "${tlsCert}"

  step "Setting up VerifierOrg MSP"
  local orgMspDir="${verifierOrgDir}/msp"
  mkdir -p "${orgMspDir}/cacerts" "${orgMspDir}/tlscacerts"
  cp "${caFabricDir}/ca-cert.pem" "${orgMspDir}/cacerts/ca-cert.pem"
  cp "${verifierOrgDir}/peers/peer0.verifier.tessera.com/tls/ca.crt" "${orgMspDir}/tlscacerts/ca-cert.pem"
  writeMSPConfig "${orgMspDir}" "ca-cert.pem"

  mkdir -p "${peerMspDir}/cacerts" "${peerMspDir}/tlscacerts"
  cp "${caFabricDir}/ca-cert.pem" "${peerMspDir}/cacerts/ca-cert.pem"
  cp "${verifierOrgDir}/peers/peer0.verifier.tessera.com/tls/ca.crt" "${peerMspDir}/tlscacerts/ca-cert.pem"
  writeMSPConfig "${peerMspDir}" "ca-cert.pem"

  mkdir -p "${adminMspDir}/cacerts"
  cp "${caFabricDir}/ca-cert.pem" "${adminMspDir}/cacerts/ca-cert.pem"
  writeMSPConfig "${adminMspDir}" "ca-cert.pem"

  success "VerifierOrg identities enrolled."
}

# ============================================================
# enrollComplianceOrg
# ============================================================
enrollComplianceOrg() {
  header "Enrolling ComplianceOrg identities"

  local caName="ca.compliance.tessera.com"
  local caHost="${CA_COMPLIANCE_HOST}"
  local caFabricDir="${ORG_DIR}/fabric-ca/compliance"
  local tlsCert="${caFabricDir}/tls-cert.pem"
  local complianceOrgDir="${ORG_DIR}/peerOrganizations/compliance.tessera.com"
  local caAdminHome="${complianceOrgDir}/ca-admin"

  waitForCA "https://${caHost}" "${caName}"

  step "Enrolling CA bootstrap admin for ComplianceOrg"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "${CA_COMPLIANCE_ADMIN_USER}" "${CA_COMPLIANCE_ADMIN_PASS}" \
    "${caAdminHome}/msp" "${tlsCert}"

  step "Registering ComplianceOrg identities"
  registerIdentity "${caAdminHome}" "${caName}" "compliance-admin" "adminpw"          "admin"  "${tlsCert}"
  registerIdentity "${caAdminHome}" "${caName}" "peer0.compliance" "peer0pw"          "peer"   "${tlsCert}"
  registerIdentity "${caAdminHome}" "${caName}" "compliance-user"  "complianceuserpw" "client" "${tlsCert}"

  step "Enrolling compliance-admin MSP"
  local adminMspDir="${complianceOrgDir}/users/Admin@compliance.tessera.com/msp"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "compliance-admin" "adminpw" "${adminMspDir}" "${tlsCert}"

  step "Enrolling peer0.compliance MSP"
  local peerMspDir="${complianceOrgDir}/peers/peer0.compliance.tessera.com/msp"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "peer0.compliance" "peer0pw" "${peerMspDir}" "${tlsCert}"

  step "Enrolling peer0.compliance TLS"
  local peerTlsEnrollDir="${complianceOrgDir}/peers/peer0.compliance.tessera.com/tls-enrollment"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "peer0.compliance" "peer0pw" "${peerTlsEnrollDir}" "${tlsCert}" \
    "tls" "peer0.compliance.tessera.com,localhost,127.0.0.1"

  installTLSCerts \
    "${peerTlsEnrollDir}" \
    "${complianceOrgDir}/peers/peer0.compliance.tessera.com/tls"

  step "Enrolling compliance-user MSP"
  enrollIdentity "${caAdminHome}" "${caHost}" "${caName}" \
    "compliance-user" "complianceuserpw" \
    "${complianceOrgDir}/users/compliance-user/msp" "${tlsCert}"

  step "Setting up ComplianceOrg MSP"
  local orgMspDir="${complianceOrgDir}/msp"
  mkdir -p "${orgMspDir}/cacerts" "${orgMspDir}/tlscacerts"
  cp "${caFabricDir}/ca-cert.pem" "${orgMspDir}/cacerts/ca-cert.pem"
  cp "${complianceOrgDir}/peers/peer0.compliance.tessera.com/tls/ca.crt" "${orgMspDir}/tlscacerts/ca-cert.pem"
  writeMSPConfig "${orgMspDir}" "ca-cert.pem"

  mkdir -p "${peerMspDir}/cacerts" "${peerMspDir}/tlscacerts"
  cp "${caFabricDir}/ca-cert.pem" "${peerMspDir}/cacerts/ca-cert.pem"
  cp "${complianceOrgDir}/peers/peer0.compliance.tessera.com/tls/ca.crt" "${peerMspDir}/tlscacerts/ca-cert.pem"
  writeMSPConfig "${peerMspDir}" "ca-cert.pem"

  mkdir -p "${adminMspDir}/cacerts"
  cp "${caFabricDir}/ca-cert.pem" "${adminMspDir}/cacerts/ca-cert.pem"
  writeMSPConfig "${adminMspDir}" "ca-cert.pem"

  success "ComplianceOrg identities enrolled."
}

# ============================================================
# Main
# ============================================================
main() {
  header "TESSERA — Fabric CA Identity Registration"
  checkBinaries
  checkDocker

  enrollOrdererOrg
  enrollIssuerOrg
  enrollVerifierOrg
  enrollComplianceOrg

  echo ""
  success "All TESSERA identities registered and enrolled successfully."
  info "Generated artifacts:"
  info "  ${ORG_DIR}/ordererOrganizations/"
  info "  ${ORG_DIR}/peerOrganizations/"
}

main "$@"
